name: SeaGold

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:
jobs:
  SeaGold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          yarn
          yarn seaGold
